[package]
name = "beacon"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tokio = { version = "1.28", features = ["io-util", "rt"] }
bytes = "1.4.0"
futures-util = { version = "0.3.28", default-features = false, features = ["std"] }
pin-project-lite = "0.2"
worker = "0.7.0"
pretty-bytes = "0.2.2"
serde_json = "1.0"
base64 = "0.22"
getrandom = { version = "0.2", features = ["js"] }
uuid = "1.8.0"
aes-gcm = "0.10"
aes = "0.8"
sha2 = "0.10"
md-5 = "0.10"
anyhow = "1.0.86"
reqwest = "0.12.5"
regex = "1.11.1"
once_cell = "1.21.3"
wasm-bindgen = "0.2.105"
wasm-bindgen-futures = "0.4"
gloo-timers = { version = "0.3", features = ["futures"] }

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
panic = "abort"
