name = "beacon"
main = "build/worker/shim.mjs"
compatibility_date = "2024-11-30"
minify = true
workers_dev = true

routes = [
  { pattern = "hoshiyomi.qzz.io", custom_domain = true, zone_id = "e5328b8e5f2ce079260f3be524a3087a" },
  { pattern = "ava.game.naver.com.hoshiyomi.qzz.io", custom_domain = true, zone_id = "e5328b8e5f2ce079260f3be524a3087a" },
  { pattern = "df.game.naver.com.hoshiyomi.qzz.io", custom_domain = true, zone_id = "e5328b8e5f2ce079260f3be524a3087a" },
  { pattern = "graph.instagram.com.hoshiyomi.qzz.io", custom_domain = true, zone_id = "e5328b8e5f2ce079260f3be524a3087a" },
  { pattern = "zaintest.vuclip.com.hoshiyomi.qzz.io", custom_domain = true, zone_id = "e5328b8e5f2ce079260f3be524a3087a" },
  { pattern = "support.zoom.us.hoshiyomi.qzz.io", custom_domain = true, zone_id = "e5328b8e5f2ce079260f3be524a3087a" },
  { pattern = "cache.netflix.com.hoshiyomi.qzz.io", custom_domain = true, zone_id = "e5328b8e5f2ce079260f3be524a3087a" },
  { pattern = "api24-normal.tiktokv.com.hoshiyomi.qzz.io", custom_domain = true, zone_id = "e5328b8e5f2ce079260f3be524a3087a" },
  { pattern = "cf-vod.nimo.tv.hoshiyomi.qzz.io", custom_domain = true, zone_id = "e5328b8e5f2ce079260f3be524a3087a" },
  { pattern = "space.byu.id.hoshiyomi.qzz.io", custom_domain = true, zone_id = "e5328b8e5f2ce079260f3be524a3087a" }
]

[[kv_namespaces]]
binding = "library"
id = "a9f61fcc3abf48af91a5924027ee1a1a"

[vars]
UUID = "38425afe-8466-4876-8223-f3d604ca3c18"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/hoshiyomiX/Beacon/refs/heads/master/web/index.html"
SUB_PAGE_URL  = "https://raw.githubusercontent.com/hoshiyomiX/Beacon/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/hoshiyomiX/Beacon/refs/heads/master/web/link.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/hoshiyomiX/Beacon/refs/heads/master/web/converter.html"
CHECKER_PAGE_URL = "https://raw.githubusercontent.com/hoshiyomiX/Beacon/refs/heads/master/web/checker.html"

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = false
